version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: mhart/alpine-node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{checksum "package.json"}}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: Build Typescript
          command: yarn build:tsc
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
  test:
    working_directory: ~/app
    docker:
      - image: mhart/alpine-node:10
      - image: circleci/mongo
    environment:
      MONGODB_URL: mongodb://localhost:27017
      PORT: 3000
    steps:
      - checkout
      - attach_at_workspace:
          at: ~/app
      - run:
          name: Install Bash and other tools
          command: |
            apk add --no-cache bash
      - run:
          name: Setup environment variables
          command: |
            case $CIRCLE_BRANCH in
              master)
                echo 'export NODE_ENV="production"' >> $BASH_ENV
                ;;
              *)
                echo 'export NODE_ENV="$CIRCLE_BRANCH"' >> $BASH_ENV
                ;;
              esac
      - run:
          name: Run Tests
          command: yarn test
